pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'api-tests:${BUILD_NUMBER}'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Test Image') {
            steps {
                dir('api-test-automation') {
                    script {
                        docker.build(DOCKER_IMAGE)
                    }
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir('api-test-automation') {
                    script {
                        docker.image(DOCKER_IMAGE).inside {
                            sh 'pytest'
                        }
                    }
                }
            }
        }
    }
    
    post {
        always {
            allure([
                includeProperties: false,
                jdk: '',
                properties: [],
                reportBuildPolicy: 'ALWAYS',
                results: [[path: 'api-test-automation/allure-results']]
            ])
            
            cleanWs()
        }
    }
}
